In [5]:
import pandas as pd

# Load the SPSS file
df = pd.read_stata("../data/HCMST Couples Meet 2017-2022 v2.2.dta", convert_categoricals=True)

/var/folders/lk/bg_vtzyj3fz74y0bzpbl63fm0000gn/T/ipykernel_72665/3362818719.py:4: UnicodeWarning:
One or more strings in the dta file could not be decoded using utf-8, and
so the fallback encoding of latin-1 is being used.  This can happen when a file
has been incorrectly encoded by Stata or some other software. You should verify
the string values returned are correct.
  df = pd.read_stata("../data/HCMST Couples Meet 2017-2022 v2.2.dta", convert_categoricals=True)

In [6]:
# View the first few rows
df.head()

,caseid_new,w3_Weight,w3_Weight_LGB,w3_combo_weight,w3_attrition_adj_weight,w2_weight_genpop,w2_weight_LGB,w2_combo_weight,w2_attrition_adj_weights,w1_weight_combo,...,p20_pppa1634,p20_pppa1902,p20_pppa1903,p20_pppa1904,p20_ppp22001,p20_pppa1905,p20_pppa1648,p20_ppp20072,p20_ppp20071,p20_ppp2date2020
0,53001,0.4422,NaN,0.495308,0.400185,0.3856,NaN,0.437670,0.380351,0.426861,...,Female,No,Female,No,No,No,No religion,Never,NaN,20210506.0
1,71609,0.8284,NaN,0.927891,0.879258,0.9196,NaN,1.043778,0.953948,1.295508,...,Female,No,Female,No,No,No,"Evangelical or Protestant Christian (Baptist, ...",Once a year or less,Yes,20201118.0
2,106983,0.8255,NaN,0.924643,0.706467,0.7748,NaN,0.879425,0.724682,1.126573,...,Male,Male,No,No,No,No,Catholic,A few times a year,No,20210429.0
3,121759,NaN,NaN,NaN,NaN,0.9177,NaN,1.041622,0.793093,0.933440,...,Male,Male,No,No,No,No,Other Christian religion,Once a week,Yes,20210507.0
4,158083,0.8810,NaN,0.986809,0.655467,0.8697,NaN,0.987140,0.735473,0.931291,...,Male,Male,No,No,No,No,No religion,Never,NaN,20210602.0

In [7]:
wave1_part = []
wave2_part = []
wave3_part = []
others_part = []
for column in df.columns:
    if column.startswith("w1") | column.startswith("p17"):
        wave1_part.append(column)
    elif column.startswith("w2")| column.startswith("p18")| column.startswith("p19")| column.startswith("p20"):
        wave2_part.append(column)
    elif column.startswith("w3"):
        wave3_part.append(column)
    else:
        others_part.append(column)

In [8]:
print(others_part)

['caseid_new', 'xpartner_type_cohab', 'yr_breakup_combo', 'change_in_rel_quality_w1w2']

In [10]:
df_w1 = df[wave1_part+others_part]
df_w2 = df[wave2_part+others_part]
df_w3 = df[wave3_part+others_part]

In [ ]:
df["w1_consent"]

In [ ]:
df_w1.head()

In [ ]:
df_w2.head()

In [ ]:
df_w3.head()

In [14]:
df_w1.describe(include=['category'])
#df_w1.describe()

,w1_speed_flag,w1_consent,w1_partyid7,w1_PERSNET_hom,w1_ppc10017,w1_ppc21310,w1_ppp20071,w1_ppp20072,w1_ppage,w1_ppagecat,...,p17_ppp10210,p17_ppp10211,p17_ppp10212,p17_ppp10213,p17_pppa1704,p17_pppa1705,p17_ppfs0596,p17_ppfs1480,p17_ppfs1482,xpartner_type_cohab
count,3510,3510,3394,3510,3510,3510,3394,3394,3510,3510,...,3199,3199,3199,3199,3199,3199,2888,2923,2933,2107
unique,2,1,7,4,4,8,4,7,76,7,...,2,2,2,2,2,2,7,4,6,4
top,Completed survey in over 2 minutes,"Yes, I agree to participate",Strong Democrat,Yes,Yes,Every day,No,Never,27,55-64,...,No,No,No,Yes,No,No,"Under $50,000",Very confident,Excellent,married
freq,3404,3510,695,3073,2596,2835,1453,1003,97,796,...,2807,2861,2571,1836,3105,2753,1355,1501,1338,1303