In [4]:
import pandas as pd
from narwhals.selectors import categorical

# Load the SPSS file
df = pd.read_stata("../data/HCMST Couples Meet 2017-2022 v2.2.dta", convert_categoricals=True)

/var/folders/lk/bg_vtzyj3fz74y0bzpbl63fm0000gn/T/ipykernel_78787/3861746957.py:5: UnicodeWarning:
One or more strings in the dta file could not be decoded using utf-8, and
so the fallback encoding of latin-1 is being used.  This can happen when a file
has been incorrectly encoded by Stata or some other software. You should verify
the string values returned are correct.
  df = pd.read_stata("../data/HCMST Couples Meet 2017-2022 v2.2.dta", convert_categoricals=True)

In [5]:
# View the first few rows
df.head()

,caseid_new,w3_Weight,w3_Weight_LGB,w3_combo_weight,w3_attrition_adj_weight,w2_weight_genpop,w2_weight_LGB,w2_combo_weight,w2_attrition_adj_weights,w1_weight_combo,...,p20_pppa1634,p20_pppa1902,p20_pppa1903,p20_pppa1904,p20_ppp22001,p20_pppa1905,p20_pppa1648,p20_ppp20072,p20_ppp20071,p20_ppp2date2020
0,53001,0.4422,NaN,0.495308,0.400185,0.3856,NaN,0.437670,0.380351,0.426861,...,Female,No,Female,No,No,No,No religion,Never,NaN,20210506.0
1,71609,0.8284,NaN,0.927891,0.879258,0.9196,NaN,1.043778,0.953948,1.295508,...,Female,No,Female,No,No,No,"Evangelical or Protestant Christian (Baptist, ...",Once a year or less,Yes,20201118.0
2,106983,0.8255,NaN,0.924643,0.706467,0.7748,NaN,0.879425,0.724682,1.126573,...,Male,Male,No,No,No,No,Catholic,A few times a year,No,20210429.0
3,121759,NaN,NaN,NaN,NaN,0.9177,NaN,1.041622,0.793093,0.933440,...,Male,Male,No,No,No,No,Other Christian religion,Once a week,Yes,20210507.0
4,158083,0.8810,NaN,0.986809,0.655467,0.8697,NaN,0.987140,0.735473,0.931291,...,Male,Male,No,No,No,No,No religion,Never,NaN,20210602.0

In [6]:
wave1_part = []
wave2_part = []
wave3_part = []
others_part = []
for column in df.columns:
    if column.startswith("w1") | column.startswith("p17"):
        wave1_part.append(column)
    elif column.startswith("w2")| column.startswith("p18")| column.startswith("p19")| column.startswith("p20"):
        wave2_part.append(column)
    elif column.startswith("w3"):
        wave3_part.append(column)
    else:
        others_part.append(column)

In [7]:
df_w1 = df[wave1_part+others_part]
df_w2 = df[wave2_part+others_part]
df_w3 = df[wave3_part+others_part]

In [8]:
df_w1.head()

,w1_weight_combo,w1_weight_combo_freqwt,w1_duration,w1_speed_flag,w1_consent,w1_partyid7,w1_PERSNET_hom,w1_ppc10017,w1_ppc21310,w1_ppp20071,...,p17_pppa1705,p17_pppadate2017,p17_ppfs0596,p17_ppfs1480,p17_ppfs1482,p17_ppfsdate2017,caseid_new,xpartner_type_cohab,yr_breakup_combo,change_in_rel_quality_w1w2
0,0.426861,29628.0,4158,Completed survey in over 2 minutes,"Yes, I agree to participate",Not Strong Democrat,Yes,Yes,Every day,Not asked,...,No,20171025.0,"Under $50,000",Somewhat confident,Excellent,20171227.0,53001,married,2020.0,1.0
1,1.295508,89921.0,38,Completed survey in over 2 minutes,"Yes, I agree to participate",Leans Republican,Yes,No,Every day,Yes,...,No,20180122.0,Not sure,Very confident,Excellent,20180216.0,71609,married,NaN,0.0
2,1.126573,78196.0,72,Completed survey in over 2 minutes,"Yes, I agree to participate",Strong Democrat,Yes,Yes,Every day,No,...,No,20170907.0,"Under $50,000",Only slightly confident,Good,20171216.0,106983,married,NaN,0.0
3,0.933440,64790.0,25,Completed survey in over 2 minutes,"Yes, I agree to participate",Not Strong Republican,Yes,Yes,Every day,Yes,...,No,20170914.0,"Under $50,000",Very confident,Excellent,20171212.0,121759,married,NaN,1.0
4,0.931291,64641.0,12,Completed survey in over 2 minutes,"Yes, I agree to participate",Leans Republican,Yes,Yes,Every day,Not asked,...,No,20171013.0,"$100,000 - $249,999",Very confident,Good,20180127.0,158083,unpartnered,NaN,NaN

In [9]:
df_w1['w1_pphhsize'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 3510 entries, 0 to 3509
Series name: w1_pphhsize
Non-Null Count  Dtype
--------------  -----
3510 non-null   category
dtypes: category(1)
memory usage: 3.9 KB

In [10]:
df_w1.describe(include=['category'])

,w1_speed_flag,w1_consent,w1_partyid7,w1_PERSNET_hom,w1_ppc10017,w1_ppc21310,w1_ppp20071,w1_ppp20072,w1_ppage,w1_ppagecat,...,p17_ppp10210,p17_ppp10211,p17_ppp10212,p17_ppp10213,p17_pppa1704,p17_pppa1705,p17_ppfs0596,p17_ppfs1480,p17_ppfs1482,xpartner_type_cohab
count,3510,3510,3394,3510,3510,3510,3394,3394,3510,3510,...,3199,3199,3199,3199,3199,3199,2888,2923,2933,2107
unique,2,1,7,4,4,8,4,7,76,7,...,2,2,2,2,2,2,7,4,6,4
top,Completed survey in over 2 minutes,"Yes, I agree to participate",Strong Democrat,Yes,Yes,Every day,No,Never,27,55-64,...,No,No,No,Yes,No,No,"Under $50,000",Very confident,Excellent,married
freq,3404,3510,695,3073,2596,2835,1453,1003,97,796,...,2807,2861,2571,1836,3105,2753,1355,1501,1338,1303

In [11]:
df_w1['w1_speed_flag'].unique()

['Completed survey in over 2 minutes', 'Completed survey in under 2 minutes']
Categories (2, object): ['Completed survey in over 2 minutes' < 'Completed survey in under 2 minutes']

In [12]:
df_w1["w1_consent"].unique()
consent_map = {'Yes, I agree to participate':1}
df_w1["w1_consent"] = df_w1["w1_consent"].map(consent_map)

/var/folders/lk/bg_vtzyj3fz74y0bzpbl63fm0000gn/T/ipykernel_78787/3537253023.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_w1["w1_consent"] = df_w1["w1_consent"].map(consent_map)

In [17]:
categorical_columns=[]
binary_columns=[]
for column in df_w1.columns:
    if str(df_w1[column].values).__contains__('Categories'):
        categorical_columns.append(column)
        if str(df_w1[column].values).__contains__('(2, str)'):
            binary_columns.append(column)
    print(str(df_w1[column].values))
    print('----------------------------')

[0.42686078 1.2955083  1.1265732  ... 0.38319856 0.19711515 1.715531  ]
----------------------------
[ 29628.  89921.  78196. ...  26598.  13682. 119075.]
----------------------------
[4158   38   72 ...    7    5   10]
----------------------------
['Completed survey in over 2 minutes', 'Completed survey in over 2 minutes', 'Completed survey in over 2 minutes', 'Completed survey in over 2 minutes', 'Completed survey in over 2 minutes', ..., 'Completed survey in over 2 minutes', 'Completed survey in over 2 minutes', 'Completed survey in over 2 minutes', 'Completed survey in over 2 minutes', 'Completed survey in over 2 minutes']
Length: 3510
Categories (2, object): ['Completed survey in over 2 minutes' < 'Completed survey in under 2 minutes']
----------------------------
[1, 1, 1, 1, 1, ..., 1, 1, 1, 1, 1]
Length: 3510
Categories (1, int64): [1]
----------------------------
['Not Strong Democrat', 'Leans Republican', 'Strong Democrat', 'Not Strong Republican', 'Leans Republican', ..., 'Strong Democrat', 'Leans Republican', 'Leans Democrat', 'Not Strong Democrat', 'Leans Republican']
Length: 3510
Categories (7, object): ['Strong Republican' < 'Not Strong Republican' < 'Leans Republican' < 'Undecided/Independent/Other' < 'Leans Democrat' < 'Not Strong Democrat' < 'Strong Democrat']
----------------------------
['Yes', 'Yes', 'Yes', 'Yes', 'Yes', ..., 'Yes', 'Yes', 'Yes', 'Yes', 'Yes']
Length: 3510
Categories (4, object): ['Not asked' < 'Refused' < 'Yes' < 'No']
----------------------------
['Yes', 'No', 'Yes', 'Yes', 'Yes', ..., 'Yes', 'Yes', 'Yes', 'Not asked', 'Not asked']
Length: 3510
Categories (4, object): ['Not asked' < 'Yes' < 'No' < 'Don't know/not sure']
----------------------------
['Every day', 'Every day', 'Every day', 'Every day', 'Every day', ..., 'Every day', 'Not asked', 'Every day', 'Not asked', 'Not asked']
Length: 3510
Categories (8, object): ['Not asked' < 'Refused' < 'Every day' < 'At least once a week but not every day' < 'About once a week' < 'About once a month' < 'Less than once a month' < 'Never']
----------------------------
['Not asked', 'Yes', 'No', 'Yes', 'Not asked', ..., 'Not asked', 'Yes', 'Not asked', 'Not asked', 'No']
Length: 3510
Categories (4, object): ['Not asked' < 'Refused' < 'Yes' < 'No']
----------------------------
['Never', 'A few times a year', 'A few times a year', 'Once a week', 'Once a year or less', ..., 'Never', 'A few times a year', 'Once a year or less', 'Once a week', 'Once or twice a month']
Length: 3510
Categories (7, object): ['Refused' < 'More than once a week' < 'Once a week' < 'Once or twice a month' < 'A few times a year' < 'Once a year or less' < 'Never']
----------------------------
[48, 68, 39, 54, 48, ..., 30, 42, 23, 34, 21]
Length: 3510
Categories (76, int64): [18 < 19 < 20 < 21 ... 90 < 91 < 92 < 93]
----------------------------
['45-54', '65-74', '35-44', '45-54', '45-54', ..., '25-34', '35-44', '18-24', '25-34', '18-24']
Length: 3510
Categories (7, object): ['18-24' < '25-34' < '35-44' < '45-54' < '55-64' < '65-74' < '75+']
----------------------------
['45-59', '60+', '30-44', '45-59', '45-59', ..., '30-44', '30-44', '18-29', '30-44', '18-29']
Length: 3510
Categories (4, object): ['18-29' < '30-44' < '45-59' < '60+']
----------------------------
['HIGH SCHOOL GRADUATE - high school DIPLOMA or..., 'Some college, no degree', 'Associate degree', 'HIGH SCHOOL GRADUATE - high school DIPLOMA or..., 'Some college, no degree', ..., 'HIGH SCHOOL GRADUATE - high school DIPLOMA or..., 'Some college, no degree', 'HIGH SCHOOL GRADUATE - high school DIPLOMA or..., 'Bachelors degree', 'HIGH SCHOOL GRADUATE - high school DIPLOMA or...]
Length: 3510
Categories (14, object): ['No formal education' < '1st, 2nd, 3rd, or 4th grade' < '5th or 6th grade' < '7th or 8th grade' ... 'Associate degree' < 'Bachelors degree' < 'Masters degree' < 'Professional or Doctorate degree']
----------------------------
['High school', 'Some college', 'Some college', 'High school', 'Some college', ..., 'High school', 'Some college', 'High school', 'Bachelor's degree or higher', 'High school']
Length: 3510
Categories (4, object): ['Less than high school' < 'High school' < 'Some college' < 'Bachelor's degree or higher']
----------------------------
['2+ Races, Non-Hispanic', 'White, Non-Hispanic', 'White, Non-Hispanic', 'White, Non-Hispanic', 'White, Non-Hispanic', ..., 'White, Non-Hispanic', 'White, Non-Hispanic', 'White, Non-Hispanic', 'Hispanic', 'Other, Non-Hispanic']
Length: 3510
Categories (5, object): ['White, Non-Hispanic' < 'Black, Non-Hispanic' < 'Other, Non-Hispanic' < 'Hispanic' < '2+ Races, Non-Hispanic']
----------------------------
['Yes', 'Yes', 'Yes', 'Yes', 'Yes', ..., 'Yes', 'Yes', 'Yes', 'No', 'No']
Length: 3510
Categories (3, object): ['Refused' < 'No' < 'Yes']
----------------------------
['No', 'No', 'No', 'No', 'No', ..., 'No', 'No', 'No', 'Yes', 'No']
Length: 3510
Categories (3, object): ['Refused' < 'No' < 'Yes']
----------------------------
['Yes', 'No', 'No', 'No', 'No', ..., 'No', 'No', 'No', 'No', 'Yes']
Length: 3510
Categories (3, object): ['Refused' < 'No' < 'Yes']
----------------------------
['No', 'No', 'No', 'No', 'No', ..., 'No', 'No', 'No', 'No', 'No']
Length: 3510
Categories (3, object): ['Refused' < 'No' < 'Yes']
----------------------------
['No', 'No', 'No', 'No', 'No', ..., 'No', 'No', 'No', 'No', 'No']
Length: 3510
Categories (3, object): ['Refused' < 'No' < 'Yes']
----------------------------
['No', 'No', 'No', 'No', 'No', ..., 'No', 'No', 'No', 'No', 'No']
Length: 3510
Categories (3, object): ['Refused' < 'No' < 'Yes']
----------------------------
[1, 1, 1, 1, 1, ..., 1, 1, 1, 0, 0]
Length: 3510
Categories (3, object): ['Refused' < 0 < 1]
----------------------------
[0, 0, 0, 0, 0, ..., 0, 0, 0, 1, 0]
Length: 3510
Categories (3, object): ['Refused' < 0 < 1]
----------------------------
[1, 0, 0, 0, 0, ..., 0, 0, 0, 0, 1]
Length: 3510
Categories (3, object): ['Refused' < 0 < 1]
----------------------------
[0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0]
Length: 3510
Categories (3, object): ['Refused' < 0 < 1]
----------------------------
[0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0]
Length: 3510
Categories (3, object): ['Refused' < 0 < 1]
----------------------------
[0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0]
Length: 3510
Categories (3, object): ['Refused' < 0 < 1]
----------------------------
[0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0]
Length: 3510
Categories (3, object): ['Refused' < 0 < 1]
----------------------------
[0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0]
Length: 3510
Categories (3, object): ['Refused' < 0 < 1]
----------------------------
[0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0]
Length: 3510
Categories (3, object): ['Refused' < 0 < 1]
----------------------------
[0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0]
Length: 3510
Categories (3, object): ['Refused' < 0 < 1]
----------------------------
[0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0]
Length: 3510
Categories (3, object): ['Refused' < 0 < 1]
----------------------------
[0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0]
Length: 3510
Categories (3, object): ['Refused' < 0 < 1]
----------------------------
[0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0]
Length: 3510
Categories (3, object): ['Refused' < 0 < 1]
----------------------------
[0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0]
Length: 3510
Categories (3, object): ['Refused' < 0 < 1]
----------------------------
[0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0]
Length: 3510
Categories (3, object): ['Refused' < 0 < 1]
----------------------------
['Female', 'Female', 'Male', 'Male', 'Male', ..., 'Female', 'Female', 'Female', 'Female', 'Female']
Length: 3510
Categories (2, object): ['Male' < 'Female']
----------------------------
['Yes', 'Yes', 'No', 'Yes', 'Yes', ..., 'Yes', 'No', 'Yes', 'Yes', 'No']
Length: 3510
Categories (2, object): ['No' < 'Yes']
----------------------------
[1, 2, 5, 4, 1, ..., 2, 2, 1, 3, 3]
Length: 3510
Categories (11, int64): [1 < 2 < 3 < 4 ... 8 < 9 < 10 < 12]
----------------------------
['A one-family house detached from any other ho..., 'A one-family house detached from any other ho..., 'A one-family house detached from any other ho..., 'A one-family house detached from any other ho..., 'A one-family house detached from any other ho..., ..., 'A one-family house detached from any other ho..., 'A building with 2 or more apartments', 'A building with 2 or more apartments', 'A building with 2 or more apartments', 'A one-family house detached from any other ho...]
Length: 3510
Categories (5, object): ['A one-family house detached from any other ho... < 'A one-family house attached to one or more ho... < 'A building with 2 or more apartments' < 'A mobile home' < 'Boat, RV, van, etc.']
----------------------------
['$60,000 to $74,999', '$50,000 to $59,999', '$85,000 to $99,999', '$100,000 to $124,999', '$75,000 to $84,999', ..., '$50,000 to $59,999', '$40,000 to $49,999', '$25,000 to $29,999', '$35,000 to $39,999', '$85,000 to $99,999']
Length: 3510
Categories (21, object): ['Less than $5,000' < '$5,000 to $7,499' < '$7,500 to $9,999' < '$10,000 to $12,499' ... '$150,000 to $174,999' < '$175,000 to $199,999' < '$200,000 to $249,999' < '$250,000 or more']
----------------------------
['$40K-$75K', '$40K-$75K', '$75K-$125K', '$75K-$125K', '$75K-$125K', ..., '$40K-$75K', '$40K-$75K', '<$40K', '<$40K', '$75K-$125K']
Length: 3510
Categories (4, object): ['<$40K' < '$40K-$75K' < '$75K-$125K' < '>$125K']
----------------------------
['Married', 'Married', 'Married', 'Married', 'Divorced', ..., 'Married', 'Divorced', 'Never married', 'Divorced', 'Never married']
Length: 3510
Categories (6, object): ['Married' < 'Widowed' < 'Divorced' < 'Separated' < 'Never married' < 'Living with partner']
----------------------------
['Non-Metro', 'Non-Metro', 'Metro', 'Metro', 'Metro', ..., 'Metro', 'Metro', 'Metro', 'Metro', 'Metro']
Length: 3510
Categories (2, object): ['Non-Metro' < 'Metro']
----------------------------
['Midwest', 'West', 'West', 'Northeast', 'West', ..., 'West', 'South', 'Midwest', 'South', 'Northeast']
Length: 3510
Categories (4, object): ['Northeast' < 'Midwest' < 'South' < 'West']
----------------------------
['East-North Central', 'Pacific', 'Pacific', 'Mid-Atlantic', 'Mountain', ..., 'Mountain', 'South Atlantic', 'East-North Central', 'South Atlantic', 'New England']
Length: 3510
Categories (9, object): ['New England' < 'Mid-Atlantic' < 'East-North Central' < 'West-North Central' ... 'East-South Central' < 'West-South Central' < 'Mountain' < 'Pacific']
----------------------------
['Owned or being bought by you or someone in yo..., 'Owned or being bought by you or someone in yo..., 'Owned or being bought by you or someone in yo..., 'Owned or being bought by you or someone in yo..., 'Owned or being bought by you or someone in yo..., ..., 'Owned or being bought by you or someone in yo..., 'Rented for cash', 'Rented for cash', 'Rented for cash', 'Owned or being bought by you or someone in yo...]
Length: 3510
Categories (3, object): ['Owned or being bought by you or someone in yo... < 'Rented for cash' < 'Occupied without payment of cash rent']
----------------------------
[0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0]
Length: 3510
Categories (3, int64): [0 < 1 < 2]
----------------------------
[0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0]
Length: 3510
Categories (5, int64): [0 < 1 < 2 < 3 < 6]
----------------------------
[0, 0, 2, 0, 0, ..., 0, 0, 0, 0, 0]
Length: 3510
Categories (5, int64): [0 < 1 < 2 < 3 < 4]
----------------------------
[0, 0, 0, 0, 0, ..., 0, 0, 0, 1, 0]
Length: 3510
Categories (4, int64): [0 < 1 < 2 < 3]
----------------------------
[1, 2, 3, 4, 1, ..., 2, 2, 1, 2, 3]
Length: 3510
Categories (10, int64): [1 < 2 < 3 < 4 ... 7 < 8 < 9 < 12]
----------------------------
['Working - as a paid employee', 'Working - as a paid employee', 'Working - as a paid employee', 'Working - as a paid employee', 'Working - as a paid employee', ..., 'Working - as a paid employee', 'Working - self-employed', 'Working - as a paid employee', 'Working - as a paid employee', 'Working - as a paid employee']
Length: 3510
Categories (7, object): ['Working - as a paid employee' < 'Working - self-employed' < 'Not working - on temporary layoff from a job' < 'Not working - looking for work' < 'Not working - retired' < 'Not working - disabled' < 'Not working - other']
----------------------------
['gen pop', 'gen pop', 'gen pop', 'gen pop', 'gen pop', ..., 'LGB sample', 'LGB sample', 'LGB sample', 'LGB sample', 'LGB sample']
Length: 3510
Categories (2, object): ['LGB sample' < 'gen pop']
----------------------------
['section 1: partnered adults', 'section 1: partnered adults', 'section 1: partnered adults', 'section 1: partnered adults', 'section 2: adults with past partners', ..., 'section 1: partnered adults', 'section 1: partnered adults', 'section 1: partnered adults', 'section 1: partnered adults', 'section 1: partnered adults']
Length: 3510
Categories (3, object): ['section 1: partnered adults' < 'section 2: adults with past partners' < 'never partnered: not surveyed in wave 1 but i...]
----------------------------
['married', 'married', 'married', 'married', 'unpartnered, has had past partner', ..., 'married', 'partnered, not married', 'partnered, not married', 'partnered, not married', 'partnered, not married']
Length: 3510
Categories (4, object): ['married' < 'partnered, not married' < 'unpartnered, has had past partner' < 'never had a partner']
----------------------------
['married', 'married', 'married', 'married', 'unpartnered', ..., 'married', 'in unmarried noncohab partnership', 'in unmarried noncohab partnership', 'in unmarried cohab partnership', 'in unmarried noncohab partnership']
Length: 3510
Categories (4, object): ['married' < 'in unmarried cohab partnership' < 'in unmarried noncohab partnership' < 'unpartnered']
----------------------------
['yes', 'yes', 'no', 'no', 'no', ..., 'yes', 'yes', 'yes', 'yes', 'yes']
Length: 3510
Categories (2, object): ['no' < 'yes']
----------------------------
['Once or twice a week', 'Once a month or less', 'Once or twice a week', '2 to 3 times a month', NaN, ..., 'Once a month or less', 'Once or twice a week', '3 to 6 times a week', 'Once a month or less', '2 to 3 times a month']
Length: 3510
Categories (6, object): ['Refused' < 'Once a day or more' < '3 to 6 times a week' < 'Once or twice a week' < '2 to 3 times a month' < 'Once a month or less']
----------------------------
['No, I have not met anyone for dating, romance..., 'No, I have not met anyone for dating, romance..., 'No, I have not met anyone for dating, romance..., 'No, I have not met anyone for dating, romance..., NaN, ..., 'No, I have not met anyone for dating, romance..., 'No, I have not met anyone for dating, romance..., 'No, I have not met anyone for dating, romance..., 'No, I have not met anyone for dating, romance..., 'Yes, I have met at least one person for datin...]
Length: 3510
Categories (3, object): ['Refused' < 'No, I have not met anyone for dating, romance... < 'Yes, I have met at least one person for datin...]
----------------------------
[NaN, NaN, NaN, NaN, NaN, ..., NaN, NaN, NaN, NaN, 'I met 2-5 different people besides [partner_n...]
Length: 3510
Categories (6, object): ['Refused' < 'One person. I met only one person besides [Pa... < 'I met 2-5 different people besides [partner_n... < 'I met 6-20 different people besides [partner_... < 'I met 21-50 different people besides [partner... < 'I met 50+ different people besides [partner_n...]
----------------------------
[NaN, NaN, NaN, NaN, NaN, ..., NaN, NaN, NaN, NaN, NaN]
Length: 3510
Categories (1, object): ['Refused']
----------------------------
[NaN, NaN, NaN, NaN, NaN, ..., NaN, NaN, NaN, NaN, 'No, I have not used a phone dating app in the...]
Length: 3510
Categories (2, object): ['No, I have not used a phone dating app in the... < 'Yes, I have used a phone dating app in the pa...]
----------------------------
[NaN, NaN, NaN, NaN, NaN, ..., NaN, NaN, NaN, NaN, NaN]
Length: 3510
Categories (4, object): ['One person. I met only one person besides [Pa... < 'I met 2-5 different people besides [partner_n... < 'I met 6-20 different people besides [partner_... < 'I met 21-50 different people besides [partner...]
----------------------------
['took the survey', 'took the survey', 'took the survey', 'took the survey', 'took the survey', ..., 'took the survey', 'took the survey', 'took the survey', 'took the survey', 'took the survey']
Length: 3510
Categories (3, object): ['took the survey' < 'excluded b.c. never had a partner, S3==2' < 'excluded b.c. refused name or nickname or ini...]
----------------------------
['straight/ non LGB', 'straight/ non LGB', 'straight/ non LGB', 'straight/ non LGB', 'straight/ non LGB', ..., 'LGB', 'LGB', 'LGB', 'LGB', 'LGB']
Length: 3510
Categories (2, object): ['straight/ non LGB' < 'LGB']
----------------------------
['NOT same-sex souple', 'NOT same-sex souple', 'NOT same-sex souple', 'NOT same-sex souple', 'NOT same-sex souple', ..., 'NOT same-sex souple', 'same_sex_couple', 'NOT same-sex souple', 'same_sex_couple', 'same_sex_couple']
Length: 3510
Categories (2, object): ['NOT same-sex souple' < 'same_sex_couple']
----------------------------
['hetero couple', 'hetero couple', 'hetero couple', 'hetero couple', 'hetero couple', ..., 'hetero couple', 'lesbian couple', 'hetero couple', 'lesbian couple', 'lesbian couple']
Length: 3510
Categories (3, object): ['hetero couple' < 'gay male couple' < 'lesbian couple']
----------------------------
['[Partner Name] is Male', '[Partner Name] is Male', '[Partner Name] is Female', '[Partner Name] is Female', '[Partner Name] is Female', ..., '[Partner Name] is Male', '[Partner Name] is Female', '[Partner Name] is Male', '[Partner Name] is Female', '[Partner Name] is Female']
Length: 3510
Categories (4, object): ['Refused' < '[Partner Name] is Male' < '[Partner Name] is Female' < '[Partner Name] is Other, please specify']
----------------------------
[NaN, NaN, NaN, NaN, NaN, ..., 'No, we are an opposite-sex couple', 'Yes, we are a same-sex couple', 'No, we are an opposite-sex couple', 'Yes, we are a same-sex couple', 'Yes, we are a same-sex couple']
Length: 3510
Categories (2, object): ['Yes, we are a same-sex couple' < 'No, we are an opposite-sex couple']
----------------------------
['No (Not Latino or Hispanic)', 'No (Not Latino or Hispanic)', 'No (Not Latino or Hispanic)', 'No (Not Latino or Hispanic)', 'No (Not Latino or Hispanic)', ..., 'No (Not Latino or Hispanic)', 'No (Not Latino or Hispanic)', 'No (Not Latino or Hispanic)', 'No (Not Latino or Hispanic)', 'No (Not Latino or Hispanic)']
Length: 3510
Categories (6, object): ['Refused' < 'No (Not Latino or Hispanic)' < 'Yes, Mexican, Mexican American, Chicano' < 'Yes, Puerto Rican' < 'Yes, Cuban' < 'Yes, Other Latino/Hispanic']
----------------------------
['White', 'White', 'White', 'Asian or Pacific Islander', 'White', ..., 'White', 'Black or African American', 'White', 'Black or African American', 'White']
Length: 3510
Categories (6, object): ['Refused' < 'White' < 'Black or African American' < 'American Indian, Aleut, or Eskimo' < 'Asian or Pacific Islander' < 'Other (please specify)']
----------------------------
[46. 71. 49. ... 23. 33. 16.]
----------------------------
['Associate degree', 'Some college, no degree', 'Some college, no degree', 'Masters degree', 'Associate degree', ..., 'HS graduate or GED', 'HS graduate or GED', 'HS graduate or GED', 'Some college, no degree', '11th grade']
Length: 3510
Categories (15, object): ['Refused' < 'No formal education' < '1st-4th grade' < '5th or 6th grade' ... 'Associate degree' < 'Bachelors degree' < 'Masters degree' < 'Professional or Doctorate degree']
----------------------------
['Professional or Doctorate degree', 'HS graduate or GED', 'Masters degree', 'No formal education', 'Associate degree', ..., 'Some college, no degree', 'HS graduate or GED', 'Associate degree', 'HS graduate or GED', 'Bachelors degree']
Length: 3510

In [15]:
print(binary_columns)

[]

In [19]:
df["w1_partyid7"].value_counts()

w1_partyid7
Strong Democrat                695
Leans Democrat                 650
Leans Republican               579
Not Strong Democrat            490
Strong Republican              482
Not Strong Republican          406
Undecided/Independent/Other     92
Name: count, dtype: int64